---
- name: Configure-nginx-server-using-ansible
  hosts: webservers
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Updata cache and install nginx
      ansible.builtin.yum:
        name: nginx
        state: present
        update_cache: yes


    - name: Enable service nginx
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: started

    - name: Copy index file
      ansible.builtin.template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: 0644

    - name: Copy css file
      ansible.builtin.copy:
        src: css
        dest: /usr/share/nginx/html
        mode: 0644


